export const translate = {
    normal: 'Normal',
    fighting: 'Lucha',
    flying: 'Volador',
    ground: 'Tierra',
    poison: 'Veneno',
    rock: 'Roca',
    bug: 'Bicho',
    ghost: 'Fantasma',
    steel: 'Metal',
    fire: 'Fuego',
    water: 'Agua',
    grass: 'Planta',
    electric: 'Eléctrico',
    psychic: 'Psíquico',
    ice: 'Hielo',
    dragon: 'Dragon',
    dark: 'Siniestro',
    fairy: 'Hada',
    unknown: 'Desconocido',
    shadow: 'Sombra'
}