export const translateAbilities = {
    stench: 'Hedor',
    drizzle: 'Llovizna',
    'speed-bost': 'Impulso',
    'battle-armor': 'Armadura batalla',
    sturdy: 'Robustez',
    damp: 'Humedad',
    limber: 'Flexibilidad',
    'sand-veil': 'Velo arena',
    static: 'Electricidad estática',
    'volt-absorb': 'Absorbe electricidad',
    'water-absorb': 'Absorbe agua',
    oblivious: 'Despiste',
    'cloud-nine': 'Aclimatación',
    'compund-eyes': 'Ojo compuesto',
    insomnia: 'Insomnio',
    'color-change': 'Cambio color',
    inmunity: 'Inmunidad',
    'flash-fire': 'Absorbe fuego',
    'shield-dust': 'Polvo escudo',
    'own-tempo': 'Ritmo propio',
    'suction-cups': 'Ventosas',
    intimidate: 'Intimidación',
    'shadow-tag': 'Sombra trampa',
    'rough-skin': 'Piel tosca',
    'wonder-guard': 'Superguarda',
    levitate: 'Levitación',
    'effect-spore': 'Efecto espora',
    synchronize: 'sincronía',
    'clear-body': 'Cuerpo puro',
    'natural cure': 'Cura natural',
    'lightning-rod': 'Pararrayos',
    'serene-grace': 'Dicha',
    'swift-swim': 'Nado rápido',
    chlorophyll: 'Clorofila',
    illuminate: 'Iluminación',
    trace: 'Calco',
    'huge-power': 'Potencia',
    'poison-point': 'Punto tóxico',
    'inner-focus': 'Fuerza mental',
    'magma-armor': 'Escudo magma',
    'water-veil': 'Velo agua',
    'magnet-pull': 'Imán',
    soundproof: 'Insonorizar',
    'rain-dish': 'Cura lluvia',
    'sand-stream': 'Chorro arena',
    pressure: 'Presión',
    'thick-fat': 'Sebo',
    'early-bird': 'Madrugar',
    'flame-body': 'Cuerpo llama',
    'run-away': 'Fuga',
    'keen-eye': 'Vista lince',
    'hyper-cutter': 'Corte fuerte',
    pickup: 'Recogida',
    truant: 'Pereza',
    hustle: 'Entusiasmo',
    'cute-charm': 'Gran encanto',
    plus: 'Más',
    minus: 'Menos',
    forecast: 'Predicción',
    'sticky-hold': 'Viscosidad',
    'shed-skin': 'Mudar',
    guts: 'Agallas',
    'marvel-scale': 'Escama especial',
    'liquid-ooze': 'Viscosecreción',
    'overgrow': 'Espesura',
    blaze: 'Mar llamas',
    torrent: 'Torrente',
    swarm: 'Enjambre',
    'rock-head': 'Cabeza roca',
    drought: 'Sequía',
    'arena-trap': 'Trampa arena',
    'vital-spirit': 'Espíritu vital',
    'white-smoke': 'Humo blanco',
    'pure-power': 'Energía pura',
    'shell-armor': 'Caparazón',
    'air-lock': 'Esclusa de aire',
    'tangled-feet': 'Tumbos',
    'motor-drive': 'Electromotor',
    rivalry: 'Rivalidad',
    steadfast: 'Impasible',
    'snow-cloak': 'Manto níveo',
    gluttony: 'Gula',
    'anger-point': 'Irascible',
    unburden: 'Liviano',
    heatproof: 'Ignífugo',
    simple: 'Simple',
    'dry-skin': 'Piel seca',
    download: 'Descarga',
    'iron-fist': 'Puño férreo',
    'poison-heal': 'Antídoto',
    adaptability: 'Adaptable',
    'skill-link': 'Encadenado',
    hydration: 'Hidratación',
    'solar-power': 'Poder solar',
    'quick-feet': 'Pies rápidos',
    normalize: 'Normalidad',
    sniper: 'Francotirador',
    'magic-guard': 'Muro mágico',
    'no-guard': 'Indefenso',
    stall: 'Rezagado',
    technician: 'Experto',
    'leaf-guard': 'Defensa hoja',
    klutz: 'Zoquete',
    'mold-breaker': 'Rompemoldes',
    'super-luck': 'Afortunado',
    aftermath: 'Detonación',
    anticipation: 'Anticipación',
    forewarm: 'Alerta',
    unaware: 'Ignorante',
    'tinted-lens': 'Cromolente',
    filter: 'Filtro',
    'slow-start': 'Inicio lento',
    scrappy: 'Intrépido',
    'storm-drain': 'Colector',
    'ice-body': 'Gélido',
    'solid-rock': 'Roca sólida',
    'snow-warning': 'Nevada',
    'honey-gather': 'Recogemiel',
    frisk: 'Cacheo',
    reckless: 'Audaz',
    multitype: 'Multitipo',
    'flower-gift': 'Don floral',
    'bad-dreams': 'Mal sueño',
    pickpocket: 'Hurto',
    'sheer-force': 'Potencia bruta',
    contrary: 'Respondón',
    unnerve: 'Nerviosismo',
    defiant: 'Flaqueza',
    'cursed-body': 'Cuerpo maldito',
    healer: 'Alma cura',
    'friend-guard': 'Compiescolta',
    'weak-armor': 'Armadura frágil',
    'heavy-metal': 'Metal pesado',
    'light-metal': 'Metal liviano',
    multiscale: 'Multiescamas',
    'toxic-boost': 'Ímpetu tóxico',
    'flare-boost': 'Ímpetu ardiente',
    harvest: 'Cosecha',
    telepathy: 'Telepatía',
    moody: 'Veleta',
    overcoat: 'Funda',
    'poison-touch': 'Toque tóxico',
    regenerator: 'Regeneración',
    'big-pecks': 'Sacapecho',
    'sand-rush': 'Ímpetu arena',
    'wonder-skin': 'Piel milagro',
    analytic: 'Cálculo final',
    illusion: 'Ilusión',
    imposter: 'Impostor',
    infiltrator: 'Allanamiento',
    mummy: 'Momia',
    moxie: 'Autoestima',
    justified: 'Justicieron',
    rattled: 'Cobardía',
    'magic-bounce': 'Espejo mágico',
    'sap-sipper': 'Herbívoro',
    prankster: 'Bromista',
    'sand-force': 'Poder arena',
    'iron-barbs': 'Punto acero',
    'zen-mode': 'Modo daruma',
    'victory-star': 'Tinovictoria',
    turboblaze: 'Turbollama',
    teravolt: 'Terravoltaje',
    'aroma-veil': 'Velo aroma',
    'flower-veil': 'Velo flor',
    'cheek-pouch': 'Carrillo',
    protean: 'Mutatipo',
    'fur-coat': 'Pelaje recio',
    magician: 'Prestidigitador',
    bulletproof: 'Antibalas',
    competitive: 'Tenacidad',
    'strong-jaw': 'Mandíbula fuerte',
    refrigerate: 'Piel helada',
    'sweet-veil': 'Velo dulce',
    'stance-change': 'Cambio táctico',
    'gale-wings': 'Alas vendaval',
    'mega-launcher': 'Megadisparador',
    'grass-pelt': 'Manto frondoso',
    symbiosis: 'Simbiosis',
    'tough-claws': 'Garra dura',
    pixilate: 'Piel feérica',
    gooey: 'Baba',
    aerilate: 'Piel celeste',
    'parental-bond': 'Amor filial',
    'dark-aura': 'Aura oscura',
    'fairy-aura': 'Aura feérica',
    'aura-break': 'Rompeaura',
    'primordial-sea': 'Mar de albor',
    'desolate-land': 'Tierra de ocaso',
    'delta-stream': 'Ráfaga delta',
    stamina: 'Firmeza',
    'wimp-out': 'Huida',
    'emergency-exit': 'Retirada',
    'water-compaction': 'Hidrorrefuerzo',
    merciless: 'Ensañamiento',
    'shields-down': 'Escudo limitado',
    stakeout: 'Vigilante',
    'water-bubble': 'Pompa',
    steelworker: 'Acero templado',
    berserk: 'Cólera',
    'slush-rush': 'Quitanieves',
    'long-reach': 'Remoto',
    'liquid-voice': 'Voz fluida',
    triage: 'Primer auxilio',
    galvanize: 'Piel eléctrica',
    'surge-surfer': 'Cola surf',
    schooling: 'Banco',
    disguise: 'Disfraz',
    'battle-bond': 'Fuerte afecto',
    'power-construct': 'Agrupamiento',
    corrosion: 'Corrosión',
    comatose: 'Letargo perenne',
    'queenly-majesty': 'Regia presencia',
    'innards-out': 'Revés',
    dancer: 'Pareja de baile',
    battery: 'Batería',
    fluffy: 'Peluche',
    dazzling: 'Cuerpo vívido',
    'soul-heart': 'Coránima',
    'tangling hair': 'Rizos rebeldes',
    receiver: 'Receptor',
    'power-of-alchemy': 'Reacción química',
    'beast-boost': 'Ultraimpulso',
    'rks-system': 'Sistema alfa',
    'electric-surge': 'Electrogénesis',
    'psychic-surge': 'Psicogénesis',
    'misty-surge': 'Nebulogénesis',
    'grassy-surge': 'Herbogénesis',
    'full-metal-body': 'Guardia metálica',
    'shadow-shield': 'Guardia espectro',
    'prism-armor': 'Armadura prisma',
    neuroforce: 'Fuerza cerebral',
    'intrepid-sword': 'Espada indómita',
    'dauntless-shield': 'Escudo recio',
    libero: 'Líbero',
    'ball-fetch': 'Recogebolas',
    'cotton-down': 'Pelusa',
    'propeller-tail': 'Hélice caudal',
    'mirror-armor': 'Coraza reflejo',
    'gulp-missile': 'Tragamisil',
    stalwart: 'Acérrimo',
    'steam-engine': 'Combustible',
    'punk-rock': 'Punk rock',
    'sand-spit': 'Expulsarena',
    'ice-scales': 'Escama de hielo',
    ripen: 'Maduración',
    'ice-face': 'Cara de hielo',
    'power-spot': 'Fuente energía',
    mimicry: 'Mimetismo',
    'screen-cleaner': 'Antibarrera',
    'steely-spirit': 'Alma acerada',
    'perish-body': 'Cuerpo mortal',
    'wandering-spirit': 'Alma errante',
    'gorilla-tactics': 'Monotema',
    'neutralizing-gas': 'Gas reactivo',
    'pastel-veil': 'Velo pastel',
    'hunger-switch': 'Mutapetito',
    'quick-draw': 'Mano rápida',
    'unseen-fist': 'Puño invisible',
    'curious-medicine': 'Medicina extraña',
    transistor: 'Transistor',
    'dragons-maw': 'Mandíbula dragón',
    'chilling-neigh': 'Relincho blanco',
    'grim-neigh': 'Relincho negro',
    'as-one': 'Unidad ecuestre',
    'lingering-aroma': 'Olor persistente',
    'seed-sower': 'Disemillar',
    'thermal-exchange': 'Termoconversión',
    'anger-shell': 'Coraza ira',
    'purifying-salt': 'Sal purificadora',
    'well-baked-body': 'Cuerpo horneado',
    'wind-rider': 'Surcavientos',
    'guard-dog': 'Perro guardián',
    'rocky-payload': 'Transportarrocas',
    'wind-power': 'Energía eólica',
    'zero-to-zero': 'Cambio heroico',
    commander: 'Comandar',
    electromorphosis: 'Dinamo',
    protosynthesis: 'Paleosíntesis',
    'quark-drive': 'Carga cuark',
    'good-as-gold': 'Cuerpo áureo',
    'vessel-of-ruin': 'Caldero debacle',
    'sword-of-ruin': 'Espada debacle',
    'tablets-of-ruin': 'Tablilla debacle',
    'beads-of-ruin': 'Abalorio debacle',
    'orichalcum-pulse': 'Latido oricalco',
    'hadron-engine': 'Motor hadrónico',
    opportunist: 'Oportunista',
    'cud-shew': 'Rumia',
    'sharpness': 'Cortante',
    'supreme-overlord': 'General supremo',
    costar: 'Unísono',
    'toxic-debris': 'Capa tóxica',
    'armor-tail': 'Cola armadura',
    'earth-eater': 'Geofagia',
    'mycelium-might': 'Poder fúngico'
}